title: AW
subtitle: Automate Workflow Stories
author: Ashung Hung
email: ashung.hung@gmail.com
description: Automate Workflow for UI Design, UI设计自动化工作流程
keywords: [UI, GUI, Photoshop, Illustrator, Sketch, Automate, Automation, Workflow, Interface Design, UI设计, 界面设计, 自动化, 工作流]
baseurl: ""
url: /
permalink: "/stories/:title.html"
exclude: ["README.md"]
lang: zh_CN
timezone: Asia/shanghai
paginate: 10
paginate_path: "/stories/page:num/"
markdown: kramdown
kramdown:
  auto_ids: false
  smart_quotes: apos,apos,quot,quot
sass:
  style: compressed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comment: true
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "home"

sns:
  - title: dribbble
    url: "https://dribbble.com/ashung"
  - title: behance
    url: "https://behance.net/ashung"
  - title: github
    url: "https://github.com/Ashung"
  - title: weibo
    url: "http://weibo.com/ashung"
