title: AW
subtitle: AutomateWorkflow
author: Ashung Hung
email: ashung.hung@gmail.com
description: Automate Workflow for UI Design, UI设计自动化工作流程
keywords: [UI, GUI, Photoshop, Illustrator, Sketch, Automate, Automation, Workflow, Interface Design, UI设计, 界面设计, 自动化, 工作流]
baseurl: ""
url: /
permalink: "/recipes/:title.html"
exclude: ["README.md"]
lang: zh_CN
timezone: Asia/shanghai
paginate: 8
paginate_path: "/recipes/page:num/"
kramdown:
  auto_ids: false
sass:
  style: compressed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comment: true
#      permalink: "/recipes/:title.html"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "home"
  -
    scope:
      path: ""
      type: "book"
    values:
      layout: "book"

collections:
  book:
    output: true

sns:
  - title: dribbble
    url: "https://dribbble.com/ashung"
  - title: behance
    url: "https://behance.net/ashung"
  - title: github
    url: "https://github.com/Ashung"
  - title: weibo
    url: "http://weibo.com/ashung"
    
    
    
yes: 
  a:
    b: ddd



