title: AW
author: Ashung Hung
email: ashung.hung@gmail.com
description: Automate Workflow for UI Design, UI设计自动化工作流程
keywords: [UI, GUI, Photoshop, Illustrator, Sketch, Automate, Automation, Workflow, Interface Design,
          UI设计, 界面设计, 自动化, 工作流]
baseurl: "/"
url: ashung.github.io
permalink: none
exclude: ["README.md"]
lang: zh_CN
timezone: Asia/shanghai

sns:
  - title: dribbble
    url: https://dribbble.com/ashung
  - title: behance
    url: https://behance.net/ashung
  - title: github
    url: https://github.com/Ashung
  - title: weibo
    url: http://weibo.com/ashung

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: false
  footnote_nr: 1
