title: Speedup Design Workflow
email: ashung.hung@foxmail.com
description: Write an site description.
keywords: [GUI, Photoshop]
baseurl: ""
permalink: none
exclude: ["README.md"]
timezone: Asia/Beijing

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

dribbble_username: ashung
behance_username:  ashung
github_username:   ashung
weibo_username:    ashung
twitter_username:  ashung

# Build settings
markdown: kramdown

kramdown:
  input: GFM

