title: Code for Design
author: Ashung Hung
email: ashung.hung@gmail.com
description: Automate Workflow for UI Design, UI设计自动化工作流程
keywords: [Sketch, Automation, Workflow, Interface Design, UI设计, 界面设计, 自动化, 工作流]
baseurl: "/"
url: "https://ashung.github.io"
permalink: "/posts/:title.html"
exclude: ["README.md", "node_modules/*", "package.json", "toPDF.js"]
lang: zh_CN
timezone: Asia/shanghai
paginate: 100
paginate_path: "/posts/page:num/"
gems: [jekyll-paginate]
markdown: kramdown
kramdown:
  auto_ids: true
#  smart_quotes: apos,apos,quot,quot
sass:
  style: compressed
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      comment: true
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: post
#   - scope:
#       path: ""
#       type: book
#     values:
#       layout: book

# collections:
#   book:
#     output: true
#     permalink: /:collection/:path

sns:
  - title: Behance
    url: "https://behance.net/ashung"
  - title: dribbble
    url: "https://dribbble.com/ashung"
  - title: GitHub
    url: "https://github.com/Ashung"
