title: AW
author: Ashung Hung
email: ashung.hung@gmail.com
description: Write an site description.
keywords: [GUI, Photoshop]
baseurl: "/"
url: ashung.github.io
permalink: none
exclude: ["README.md"]
lang: zh_CN
timezone: Asia/shanghai

sns:
  dribbble:
    url: https://dribbble.com/ashung
  behance:
    url: https://behance.net/ashung
  github:
    url: https://github.com/Ashung
  weibo:
    url: http://weibo.com/ashung

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: false
  footnote_nr: 1
