title: Speedup Design Workflow
email: ashung.hung@foxmail.com
description: Write an site description.
keywords: [GUI, Photoshop]
baseurl: ""
permalink: none
exclude: ["README.md"]
timezone: Asia/shanghai

sns:
  dribbble:
    name: Ashung Hung
    url: https://dribbble.com/ashung
  behance:
    name: Ashung Hung
    url: https://www.behance.net/ashung
  github:
    name: Ashung
    url: https://github.com/Ashung
  weibo:
    name: Ashung
    url: http://weibo.com/ashung

# Build settings
markdown: kramdown

kramdown:
  input: GFM

