title: AW
subtitle: Automate Workflow
author: Ashung Hung
email: ashung.hung@gmail.com
description: Automate Workflow for UI Design, UI设计自动化工作流程
keywords: [UI, GUI, Photoshop, Illustrator, Sketch, Automate, Automation, Workflow, Interface Design, UI设计, 界面设计, 自动化, 工作流]
baseurl: "/"
url: "http://ashung.github.io"
permalink: "/stories/:title.html"
exclude: ["README.md"]
lang: zh_CN
timezone: Asia/shanghai
paginate: 16
paginate_path: "/stories/page:num/"
gems: [jekyll-paginate]
markdown: kramdown
kramdown:
  auto_ids: false
#  smart_quotes: apos,apos,quot,quot
sass:
  style: compressed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comment: true
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"

sns:
  - title: dribbble
    url: "https://dribbble.com/ashung"
  - title: Behance
    url: "https://behance.net/ashung"
  - title: GitHub
    url: "https://github.com/Ashung"
  - title: Weibo
    url: "http://weibo.com/ashung"
